### ISSUE TITLE
Dockerfile is missing

### ISSUE THREAD

**Issue by cluk1** [rchampourlier/calsync#4]
Hi, 
thanks a lot for setting up this repo.
In trying out your code I recognized that the README.md is mentioning a Dockerfile, but this file is missing in the repo.
It would be great if you could add it as it would make testing and experimenting a lot easier for me.
Thanks a lot!
Christoph

**Comment by rchampourlier** [comment]
Hi @cluk33 !

Thanks for your interest, I'll see what I can do :)

**Comment by rchampourlier** [comment]
Should be fixed by #5
