### ISSUE TITLE
Timezone Issue when run from within Docker

### ISSUE THREAD

**Issue by cluk1** [rchampourlier/calsync#6]
After applying a few minor tweaks I got the code working from inside docker (thanks for supplying the Dockerfile). 
I am syncing from Caldav (Zimbra) to Google. 
All the event seem to be correctly created in the Google calendar but are shifted by two hours. e.g. the event starts at 10 am instead of 8am. This looks like a timezone issue to me (CET).
I tried to run the docker container with the correct timezone but this did not change anything:
docker run -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro --rm -it calsync
Any help is greatly appreciated!
Thanks a lot for your work!

**Comment by rchampourlier** [comment]
Hi @cluk33 ! That's something I encountered too when trying to run it Docker. I didn't have time to investigate. I'll try again!
